SELECT DISTINCT
   TO_CHAR(sysdate,'DD-MON-YYYY hh24:mi:ss') AS PRINTDATE,
   DATESCHEDULED,
   CLIENTNAME,
   STUDYNAME,
   PRODUCTNAME,
   BATCHNAME,
   STGCONDITIONNAME,
   STGCHAMBER,
   STGORIENTATION,
   TIMEPOINT,
   INTERVAL_HOURS,
   LWRLABNAME,
   LWR_ID,
   NVL(LWRQUANTITYNEEDED,0)||'-'||NVL(STUDYPKGTYPE,' ') AS QUANTITYNEEDED
FROM SLIM.VIEW_LMS_REPORTS@LMS_STABILITY_DATA
WHERE STUDYSTATUSID IN (11,24,25)
--AND LWRSTATUS='Requested'
AND TRUNC(DATESCHEDULED) >= DECODE($P{DATEFROMSTRING},'[]', TRUNC(DATESCHEDULED), TO_DATE($P{DATEFROMSTRING},'yyyyMMdd'))
AND TRUNC(DATESCHEDULED) <= DECODE($P{DATETOSTRING},'[]',  TRUNC(DATESCHEDULED), TO_DATE($P{DATETOSTRING},'yyyyMMdd'))
ORDER BY CLIENTNAME,TRUNC(DATESCHEDULED) DESC,STUDYNAME,PRODUCTNAME,INTERVAL_HOURS,BATCHNAME,LWR_ID
