
--! Group timepoint and conditions into Batch Number
SELECT
   BATCHNAME,
   TIMEPOINT,
   STGCONDITIONNAME,
   LISTAGG(LWR_ID,',') WITHIN GROUP (ORDER BY BATCHNAME) AS lwrs
FROM
    ELNPROD.LMS_STABILITY_DATA
GROUP BY BATCHNAME, STGCONDITIONNAME, TIMEPOINT
ORDER BY BATCHNAME, STGCONDITIONNAME, TIMEPOINT;





SELECT
   BATCHNAME,
   TIMEPOINT,
   STGCONDITIONNAME,
   LISTAGG(LWR_ID,',') WITHIN GROUP (ORDER BY BATCHNAME) AS lwrs
FROM
    ELNPROD.LMS_STABILITY_DATA
GROUP BY BATCHNAME, STGCONDITIONNAME, TIMEPOINT
ORDER BY BATCHNAME, STGCONDITIONNAME, TIMEPOINT;


----

SELECT
   BATCHNAME,
   STGCONDITIONNAME,
   TIMEPOINT,
   DATESCHEDULED,
   DATEPULLED
FROM
    ELNPROD.LMS_STABILITY_DATA
WHERE
    BATCHNAME LIKE '205-0258'
GROUP BY BATCHNAME, TIMEPOINT, STGCONDITIONNAME, DATESCHEDULED, DATEPULLED, CLIENTNAME
ORDER BY STGCONDITIONNAME;
